AllCops:
  Exclude:
    - 'packaging/**/*'
    - 'vendor/**/*'
Style/FrozenStringLiteralComment:
  Enabled: False
Metrics/MethodLength:
  Enabled: False
Metrics/AbcSize:
  Enabled: False
ClassLength:
  Enabled: False
ClassVars:
  Enabled: False
